### ISSUE TITLE
ValueError: volatile argument is not supported anymore. Use chainer.using_config

### ISSUE THREAD

**Issue by zhengziqiang** [pfnet-research/chainer-gan-lib#10]
Traceback (most recent call last):
  File "/media/scs4450/52d95cdd-64a0-4c37-9480-dc43778ffc5f/next/gan/chainer-gan-lib-master/train.py", line 191, in <module>
    main()
  File "/media/scs4450/52d95cdd-64a0-4c37-9480-dc43778ffc5f/next/gan/chainer-gan-lib-master/train.py", line 187, in main
    trainer.run()
  File "/usr/local/lib/python3.4/dist-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/chainer/training/trainer.py", line 302, in run
    entry.extension(self)
  File "/media/scs4450/52d95cdd-64a0-4c37-9480-dc43778ffc5f/next/gan/chainer-gan-lib-master/common/evaluation.py", line 104, in evaluation
    mean, std = inception_score(model, ims)
  File "/media/scs4450/52d95cdd-64a0-4c37-9480-dc43778ffc5f/next/gan/chainer-gan-lib-master/common/inception/inception_score.py", line 42, in inception_score
    ims_batch = Variable(ims_batch, volatile=False)
  File "/usr/local/lib/python3.4/dist-packages/chainer/variable.py", line 443, in __init__
    kwargs, volatile='volatile argument is not supported anymore. '
  File "/usr/local/lib/python3.4/dist-packages/chainer/utils/argument.py", line 4, in check_unexpected_kwargs
    raise ValueError(message)
ValueError: volatile argument is not supported anymore. Use chainer.using_config

**Comment by badaodao** [comment]
I meet the same problem... Did you solved it?Thank you very much!

**Comment by zhengziqiang** [comment]
@badaodao I use the TF==1.8.0, and it works for me. The version problem

**Comment by badaodao** [comment]
Thank you for your timely reply! It is really a version problem.
After I asked you, I solved it by modify some codes. As the Variable.volatile flag has been removed since chainer v2. 
Best wishes to you!
