### ISSUE TITLE
RuntimeError: cannot twice-differentiate an old style Function "sqrt"

### ISSUE THREAD

**Issue by SeitaroShinagawa** [pfnet-research/chainer-gan-lib#6]
Thanks for your interesting works.
I tried chainer-gan-lib/progressive, but it does not work well,

[Environments]
 chainer-4.0.0a1, cupy-3.0.0a1,  python 3.5.2, numpy 1.11.1, tensorflow 1.2.0.

The error message said, "RuntimeError: cannot twice-differentiate an old style Function "sqrt"".
It seems some trouble happened on twice-differentiate of backward().
However, I confirmed that chainer-gan-lib/wgan_gp, which also uses twice-differentiate, works for me.

All error messages are as follows:
```python
/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/cupy/core/fusion.py:659: FutureWarning: cupy.core.fusion is experimental. The interface can change in the future.
  util.experimental('cupy.core.fusion')
Exception in main training loop: cannot twice-differentiate an old style Function "sqrt"
Traceback (most recent call last):
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/training/trainer.py", line 302, in run
    entry.extension(self)
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/reporter.py", line 98, in scope
    yield
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/project/nakamura-lab07/Work/seitaro-s/chainer-gan-lib/progressive/updater.py", line 85, in update_core
    loss_dis_total.backward()
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/variable.py", line 878, in backward
    self._backward_main(retain_grad)
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/configuration.py", line 128, in using_config
    yield
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/variable.py", line 878, in backward
    self._backward_main(retain_grad)
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/variable.py", line 971, in _backward_main
    x._check_old_style_gradient()
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/variable.py", line 396, in _check_old_style_gradient
    self._old_style_grad_generator)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    main()
  File "train.py", line 131, in main
    trainer.run()
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/training/trainer.py", line 302, in run
    entry.extension(self)
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/reporter.py", line 98, in scope
    yield
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/project/nakamura-lab07/Work/seitaro-s/chainer-gan-lib/progressive/updater.py", line 85, in update_core
    loss_dis_total.backward()
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/variable.py", line 878, in backward
    self._backward_main(retain_grad)
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/configuration.py", line 128, in using_config
    yield
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/variable.py", line 878, in backward
    self._backward_main(retain_grad)
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/variable.py", line 971, in _backward_main
    x._check_old_style_gradient()
  File "/home/is/seitaro-s/.pyenv/versions/anaconda3-2.1.0/envs/chainerv4/lib/python3.5/site-packages/chainer/variable.py", line 396, in _check_old_style_gradient
    self._old_style_grad_generator)
RuntimeError: cannot twice-differentiate an old style Function "sqrt"
```

**Comment by mattya** [comment]
Thank you for reporting and sorry for inconvenience.
Current progressive growing of gan example depends on new-style (double backpropable) `sqrt` and `rdiv` functions, which are not yet merged into chainer master branch.
So you need to reinstall chainer after merging following two PRs:
  https://github.com/chainer/chainer/pull/3581
  https://github.com/chainer/chainer/pull/3615

I also added double-bp checking code https://github.com/pfnet-research/chainer-gan-lib/commit/823577655915ce0e95ddad306ea480be26fe766f

**Comment by SeitaroShinagawa** [comment]
It works! Thank you!

**Comment by takagi** [comment]
Now the both, chainer/chainer#3581 and chainer/chainer#3615, are merged to chainer master.
